refactor the hooks

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,17 +1,20 @@
 #!/usr/bin/env bash
 export HOOK_NAME=pre-commit
-export GIT_COMMON_DIR=$(git rev-parse --git-common-dir)
-export CURRENT_BRANCH=$(git branch --show-current) # git 2.22+
-# export CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
-source $GIT_COMMON_DIR/hooks/base.sh
+source $(git rev-parse --git-common-dir)/hooks/common.sh
 
-for plugin in $(find $GIT_COMMON_DIR/hooks -type d -exec basename {} \;); do
-    if [ -f "$GIT_COMMON_DIR/hooks/$plugin/$HOOK_NAME" ]; then
-        "$GIT_COMMON_DIR/hooks/$plugin/$HOOK_NAME"
-        status=$?
-        if [ $status -ne 0 ]; then
-            echo "ERROR in $plugin"
-            exit $status
-        fi
+# if [[ $CURRENT_BRANCH =~ $PROTECTED_BRANCH ]]; then
+#   echo >&2 "You can't commit directly to protected branch ($CURRENT_BRANCH)!"
+#   exit 1
+# fi
+
+find-program clang-format
+find-program perl
+
+commands=(encoding.pl format.sh)
+for subcommand in ${commands[@]}; do
+    "$GIT_COMMON_DIR/hooks/check/$subcommand"
+    status=$?
+    if [ $status -ne 0 ]; then
+        exit $status
     fi
 done
diff --git a/hooks/pre-push b/hooks/pre-push
--- a/hooks/pre-push
+++ b/hooks/pre-push
@@ -1,20 +1,22 @@
 #!/usr/bin/env bash
 export HOOK_NAME=pre-push
-export GIT_COMMON_DIR=$(git rev-parse --git-common-dir)
-export CURRENT_BRANCH=$(git branch --show-current) # git 2.22+
-# export CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
-source $GIT_COMMON_DIR/hooks/base.sh
+source $(git rev-parse --git-common-dir)/hooks/common.sh
 
-for plugin in $(find $GIT_COMMON_DIR/hooks -type d -exec basename {} \;); do
-    if [ -f "$GIT_COMMON_DIR/hooks/$plugin/$HOOK_NAME" ]; then
-        "$GIT_COMMON_DIR/hooks/$plugin/$HOOK_NAME"
-        status=$?
-        if [ $status -ne 0 ]; then
-            echo "ERROR in $plugin"
-            exit $status
-        fi
+if [[ $CURRENT_BRANCH =~ $PROTECTED_BRANCH ]]; then
+    echo >&2 "Never push code directly to the protected branch ($CURRENT_BRANCH)!"
+    exit 1
+fi
+
+push_command=$(ps -ocommand= -p $PPID)
+if [[ $push_command =~ $FORCE_PUSH_CMD ]]; then
+    echo "Think before you type."
+    $(prompt-to-confirm)
+    status=$?
+    if [ $status -ne 0 ]; then
+        echo "Abort..."
+        exit $status
     fi
-done
+fi
 
 find-program git-lfs
 git lfs pre-push "$@"
